#!/usr/bin/env bash
 sudo sed -i "/server_name _;$/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
