#!/usr/bin/env bash
# Makes server listen on port 80
sudo service nginx start
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/8080/80/g" /etc/nginx/sites-available/default
sudo service nginx restart
