#!/usr/bin/env bash
# This is a Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
i="1"
while [ $i -lt 21 ];
do
	echo "$i"
	if [ $i -eq 4 ]
	then
		echo "bad luck from china"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from japan"
	elif [ $i -eq 17 ]
	then
       		echo "bad luck from italy"
	fi
	i=$((i+1));
done
